Fix: Updated Ratatu yml workflow to get the correct exit code
Signed-off-by: rafaeljohn9 <rafaeljohb@gmail.com>

diff --git a/.github/workflows/ratatui.yml b/.github/workflows/ratatui.yml
--- a/.github/workflows/ratatui.yml
+++ b/.github/workflows/ratatui.yml
@@ -31,9 +31,10 @@ jobs:
         continue-on-error: true
         working-directory: ./ratatui
         run: |
-          echo "🎬 Running cargo tests..."
-          cargo test -- --nocapture 2>&1 | tee test_output.txt
-          echo "failed=$([ $? -eq 0 ] && echo "false" || echo "true")" >> $GITHUB_OUTPUT
+              echo "🎬 Running cargo tests..."
+              cargo test -- --nocapture 2>&1 | tee test_output.txt
+              TEST_EXIT_CODE=${PIPESTATUS[0]}
+              echo "failed=$([ $TEST_EXIT_CODE -eq 0 ] && echo "false" || echo "true")" >> $GITHUB_OUTPUT
 
       - name: 📦 Read test output
         id: testout
